export type RuleErrorCode =
  | "INVALID_ACTION"
  | "NOT_YOUR_TURN"
  | "INVALID_PHASE"
  | "UNIT_NOT_FOUND"
  | "UNIT_NOT_OWNED"
  | "UNIT_DEFEATED"
  | "UNIT_NOT_ON_BOARD"
  | "INVALID_MOVEMENT_RULE"
  | "OUT_OF_BOUNDS"
  | "ILLEGAL_MOVE"
  | "PATH_BLOCKED"
  | "DESTINATION_OCCUPIED"
  | "STALE_STATE_VERSION"
  | "MATCH_FINISHED"
  | "INVALID_COMBATANTS"
  | "SAME_OWNER_COMBAT"
  | "COMBATANT_NOT_ON_BOARD"
  | "INVALID_COMBAT_DESTINATION"
  | "INVALID_COMBAT_VALUE"
  | "VIEWER_NOT_IN_MATCH"
  | "INVALID_VISIBILITY_VIEWER"
  | "INVALID_VISIBILITY_TRANSITION"
  | "INVALID_BOARD_SIZE"
  | "INVALID_FLAG_STATE"
  | "INVALID_FLAG_DAMAGE";

export type RuleError = {
  code: RuleErrorCode;
  message: string;
  details?: Record<string, unknown>;
};
